config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "authentication#login_form"
  post "/login", to: "authentication#authenticate"
  post "/logout", to: "authentication#logout"

  get "/setup", to: "authentication#setup"

  get "/authentication/something-awful/identify", to: "authentication#something_awful_identify"
  patch "/authentication/something-awful/identify", to: "authentication#something_awful_verify", as: "authentication_something_awful_verify"

  get "/authentication/discord/callback", to: "authentication#discord_callback"
  post "/authentication/discord/disconnect", to: "authentication#disconnect_discord"

  resources :servers, except: [:new, :show]

  root to: "servers#index"
end

app/models/server.rb
# == Schema Information
#
# Table name: servers
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  discord_id :string           not null
#
class Server < ApplicationRecord
  validates :discord_id, presence: true, uniqueness: true

  has_many :server_permissions, inverse_of: :server, dependent: :destroy
  has_many :users, through: :server_permissions, inverse_of: :servers
  has_many :moderators,
    -> { where("server_permissions.moderator" => true) },
    through: :server_permissions,
    source: :user,
    inverse_of: :servers_with_mod_status

  def to_s
    name || discord_id
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  def index; end

  def new; end
end

app/views/servers/index.html.erb
<h1>Servers</h1>

<h2>Servers you're on and can add a bot to</h2>
<ul>
  <% current_user.servers_with_mod_status.order(:name).each do |server| %>
    <li><%= link_to server.name, edit_server_path(server) %></li>
  <% end %>
</ul>

<h2>Servers you're on and can't add a bot to</h2>
<ul>
  <% current_user.servers_without_mod_status.order(:name).each do |server| %>
    <li><%= server %></li>
  <% end %>
</ul>