config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "authentication#login_form"
  post "/login", to: "authentication#authenticate"
  post "/logout", to: "authentication#logout"

  get "/setup", to: "authentication#setup"

  get "/authentication/something-awful/identify", to: "authentication#something_awful_identify"
  patch "/authentication/something-awful/identify", to: "authentication#something_awful_verify", as: "authentication_something_awful_verify"

  get "/authentication/discord/callback", to: "authentication#discord_callback"
  post "/authentication/discord/disconnect", to: "authentication#disconnect_discord"

  resources :servers, except: [:new, :show]

  root to: "servers#index"
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_action :check_authentication, only: [:login_form, :authenticate]
  skip_before_action :check_setup

  def login_form; end

  def authenticate
    if (user = User.find_by(email: params[:email]))
      if user.authenticate(params[:password])
        cookies.encrypted[:user_id] = session[:user_id] = user.id
      else
        flash.alert("Login failed.")
      end
    end

    redirect_to root_path
  end

  def logout
    session.delete(:user_id)

    redirect_to login_path
  end

  def setup
    @status = SetupStatus::Overview.new(current_user)
  end

  def something_awful_identify
    taken_ids = User
      .where(something_awful_verified: true)
      .pluck(:something_awful_id)

    @available_mods = SomethingAwfulUserCache
      .where.not(something_awful_id: taken_ids)
      .order(:name)
  end

  def something_awful_verify
    if current_user.update(params.require(:user).permit(:something_awful_id))
      # trigger profile check
      redirect_to setup_path
    else
      flash.alert(current_user.errors.full_messages.to_sentence)
    end
  end

  def discord_callback
    token = DiscordOauth2.get_token(params[:code], user_id: current_user.id, hmac: params[:state])

    current_user.discord_assign_token(token)
    current_user.save!
    current_user.update_discord_id
    current_user.update_server_records

    redirect_to setup_path
  end

  def disconnect_discord
    current_user.revoke_discord

    redirect_to setup_path
  end
end

app/views/authentication/_stage.html.erb
<% list_type = stage.ordered? ? 'ol' : 'ul' %>
<<%= list_type %> class="
  stage
  <%= 'root' if stage.root? %>
">
  <% stage.sequence.each do |substage| %>
    <li class="
      <%= 'finished' if substage.finished? %>
      <%= 'next' if (next_stage = stage.ordered? && stage.sequence.find { |s| !s.finished? } == substage) %>
      <%= 'locked' if stage.ordered? && !next_stage && !substage.finished? %>
      <%= 'terminal' if substage.terminal? %>
    ">
      <% if substage.terminal? %>
        <%= render substage.template, stage: substage %>
      <% else %>
        <% unless substage.root? %>
          <h2><%= substage.name %></h2>
        <% end %>

        <%= render "stage", stage: substage %>
      <% end %>
    </li>
  <% end %>
</<%= list_type %>>

app/views/authentication/login_form.html.erb
<h1>Login</h1>

<%= form_tag login_path do %>
  <%= text_field_tag :email %>
  <%= password_field_tag :password %>

  <button>Log in</button>
<% end %>

app/views/authentication/setup.html.erb
<% if setup_finished? %>
  <h1>You're all set up!</h1>
<% else %>
  <h1>Set up your authentication</h1>
<% end %>

<%= render "stage", stage: @status %>

app/views/authentication/something_awful_identify.html.erb
<h1>Identify yourself on SomethingAwful</h1>

<%= form_for current_user, url: authentication_something_awful_verify_path do |f| %>
  <h2>Who are you?</h2>

  <%= f.select :something_awful_id, options_from_collection_for_select(@available_mods, :something_awful_id, :name, current_user.something_awful_id),
    label: "Moderators",
    include_blank: true %>

  <button>Save</button>
<% end %>