config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "authentication#login_form"
  post "/login", to: "authentication#authenticate"
  post "/logout", to: "authentication#logout"

  get "/setup", to: "authentication#setup"

  get "/authentication/something-awful/identify", to: "authentication#something_awful_identify"
  patch "/authentication/something-awful/identify", to: "authentication#something_awful_verify", as: "authentication_something_awful_verify"

  get "/authentication/discord/callback", to: "authentication#discord_callback"
  post "/authentication/discord/disconnect", to: "authentication#disconnect_discord"

  resources :servers, except: [:new, :show]

  root to: "servers#index"
end

app/models/setup_status/discord.rb
class SetupStatus::Discord < SetupStatus::Base
  SEQUENCE = [
    IdentifyYourself,
    VerifyModeratorStatus,
  ].freeze

  def name
    "Discord"
  end
end

app/models/setup_status/discord/identify_yourself.rb
class SetupStatus::Discord::IdentifyYourself < SetupStatus::Base
  def finished?
    user.discord_id.present?
  end

  def terminal?
    true
  end

  def template
    "authentication/setup/discord/identify_yourself"
  end
end

app/models/setup_status/discord/verify_moderator_status.rb
class SetupStatus::Discord::VerifyModeratorStatus < SetupStatus::Base
  def finished?
    user.servers_with_mod_status.any?
  end

  def terminal?
    true
  end

  def template
    "authentication/setup/discord/verify_moderator_status"
  end
end

app/views/authentication/setup/discord/_identify_yourself.html.erb
<% if stage.finished? %>
  <p>
    Identified as Discord ID <%= current_user.discord_id %>
  </p>

  <%= button_to "Revoke access", authentication_discord_disconnect_path %>
<% else %>
  <p>
    <%= link_to "Identify yourself with Discord", DiscordOauth2.authorise_url(user_id: current_user.id) %>
  </p>
<% end %>

app/views/authentication/setup/discord/_verify_moderator_status.html.erb
<p>You have been verified as mod for <%= current_user.servers_with_mod_status.order(:name).to_sentence %></p>